### PR TITLE
remove needless examples

### PR DESCRIPTION
**Pull request by wuyudi**
I notice the examples/ trigger the bot PR a lot of mess. So I remove it.

### CODE REVIEW

**Comment by wuyudi** [comment]
cc @Zalastax this PR doesn't introduce changes.

**Comment by Zalastax** [comment]
Are the examples useless / not working or is the issue dependabot? If dependabot is the only concern, consider instead configuring to ignore these directories https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

**Comment by wuyudi** [comment]
> Are the examples useless / not working or is the issue dependabot? If dependabot is the only concern, consider instead configuring to ignore these directories [docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

https://github.com/dependabot/dependabot-core/issues/4364

I find renovate. Maybe it works for this.

**Comment by wuyudi** [comment]
Let's turn off the robot first. renovate seems a bit complex.

**Pull request closed without merging**
