### PR TITLE
update name, dependencies

### PR DESCRIPTION
**Pull request by Spongman**
i _think_ this should allow `npm install @types/p5`

### CODE REVIEW

**Comment by Spongman** [comment]
oh, no. that's not correct. i think we need to push the build results to a separate branch with its own `package.json`.

**Comment by Zalastax** [comment]
We just need to get https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27878 merged :smile:
I've not gotten any reply for a long while though.

**Comment by Spongman** [comment]
is there some way to have this happen automatically? or is it necessary to push a new PR to them every release?

**Comment by Zalastax** [comment]
There needs to be a PR each time. I also want to automatically trigger p5.ts builds but I don't plan to implement it before the first PR is merged. There's already support for building+committing on every p5 commit in a range. Setting up a batch job in Travis + some small improvements of existing functionality would get us a long way.

**Pull request closed without merging**
